jadwal/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .calviews import CalendarView, event
from .views import index, logout


urlpatterns = [
    path('', index, name="index"),
    path('logout/', logout, name='logout'),
    path('calendar/', CalendarView.as_view(), name='calendar'),
    path('event/new/', event, name='event_new'),
    path('event/edit/<int:event_id>', event, name='event_edit'),
]

nara/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('jadwal.urls', 'jadwal'), namespace='jadwal')),
    #     path('deadline/',include('deadline.urls')),
    path('nilai/',include('nilai.urls')),
    #     path('reminder/',include('reminder.urls'))
    path('deadline/',include('deadline.urls')),
    # path('admin/', admin.site.urls),
    # path('', include(('jadwal.urls', 'jadwal'), namespace='jadwal')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('reminder/',include('reminder.urls'))
]

jadwal/models.py
from django.db import models

from django.urls import reverse
# Create your models here.


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    @property
    def get_html_url(self):
        url = reverse('jadwal:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

jadwal/forms.py
from django.forms import ModelForm, DateInput
from .models import Event


class EventForm(ModelForm):
    class Meta:
        model = Event
        # datetime-local is a HTML5 input type, format to make date time show on fields
        widgets = {
            'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        # input_formats parses HTML5 datetime-local input to datetime field
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

jadwal/views.py
from django.shortcuts import render
from django.contrib.sites import requests
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.urls import reverse

# Create your views here.


def index(request):
    return render(request, 'landing.html')


def logout(request):
    """Logs out user"""
    request.session.flush()
    return HttpResponseRedirect(reverse('jadwal:index'))

jadwal/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  <title>Nara</title>
</head>
<body>

  <h1 class="title">{% block title %}{% endblock %}</h1>
  <header>
            <nav class="navbar navbar-expand-lg navbar-light navbar-navbarcolor py-3">
                <a class="navbar-brand" href="#">
                    <img src="../../../deadline/static/deadline/images/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
                    <a style="font-style:italic;font-weight: bold;">
                        Project Nara
                    </a>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav ml-auto">
                    <li class="nav-item mr-md-5">
                        <a class="nav-link" href="#">Schedule Planner<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item mr-md-5">
                        <a class="nav-link" href="#">Your Deadline</a>
                    </li>
                    <li class="nav-item mr-md-5">
                        <a class="nav-link" href="#">Score Calculator</a>
                    </li>
                    <li class="nav-item mr-md-5">
                        <a class="nav-link" href="#">About Us</a>
                    </li>
                    </ul>
                </div>
            </nav>
        </header>

  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

jadwal/templates/calendar.html
{% extends 'base.html' %}

{% block title %}
Calendar
{% endblock %}

{% block content %}
<div class="container-fluid">

  <div class="clearfix">
    <a class="btn btn-info left" href="{% url 'jadwal:calendar' %}?{{ prev_month }}"> Previous Month </a>
    <a class="btn btn-info right" href="{% url 'jadwal:calendar' %}?{{ next_month }}"> Next Month </a>
    <a class="btn btn-info right" href="{% url 'jadwal:event_new' %}"> New Event </a>
  </div>
  <div class="container" style="margin-top: 40px;">
    <h1>
      <b>
        <i>
          Schedule Planner
        </i>
      </b>
    </h1>
  </div>
  <div class="container py-4" style="background-color: aquamarine;border-radius: 2%;">
    <div class="container">
      <div class="row" >
        <div class="container my-1 mx-3" style="width: 100%;">
          <div class="col-sm bg-white my-3 px-0" style="width: 100%;">
            {{ calendar }}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

jadwal/templates/event.html
{% extends 'base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'jadwal:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table" id="page">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

jadwal/templates/landing.html
{% load staticfiles %}
<html>
  <link rel="stylesheet" type="text/css" href="{'% static 'jadwal/static/css/styles.css' %}">
    <meta name="google-signin-client_id"
          content="180774731904-kodj5mc8sk142kej9gd12a7j2bl0gsst.apps.googleusercontent.com">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <link rel="stylesheet" type="text/css" href="{'% static 'styles.css' %}">
<head>
    <title> Nara</title>
</head>
  <body>
    <section>
      <div class="container" style="font-family: 'Montserrat';position: absolute; top:50%;left:50%;transform: translate(-50%, -50%); max-width: 70%;">
        {% block content %}
        {% if user.is_authenticated %}
        <h1 id= "gmailname" style="font-size: 80px; text-align: center;">
        Hello, <i>{{user.username}}!</i></h1>
        <h2 style="text-align: center;">Ayo tingkatkan produktivitasmu!</h2>
        <a style="position : absolute;left:50%; font-size: 20px;" href="{% url 'jadwal:logout'%}"> logout </a>
        {% else %}
          <div class="container text-center" style="font-family: 'Montserrat';position: absolute; top:50%;left:50%;transform: translate(-50%, -50%); max-width: 70%;">
            <h1><i>Project-Nara Planner</i></h1>
            <p>Project-Nara Planner adalah projek bersama yang bertujuan untuk meningkatkan produktivitas mahasiswa
              dengan mengatur rencana belajar, tenggat waktu tugas, dll.</p>
            <a href="{% url 'social:begin' backend='google-oauth2' %}">Login with GOOGLE</a>
          </div>
        {% endif %}
        {% endblock content %}
      </div>
  </section>
</body>

</html>